title: Scienceable lab # your name (or website title) here
logo: "/images/sandrine_portrait.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sandrine Muller, Eng. Msc., PhD
  <br><br>
  Hey there! 
  My name is Sandrine Muller. I am an electrical engineer from brackground (CPE Lyon/EPFL). I graduated from my PhD in neurosciences in 2017 at the faculaty of biology and medicine, UNIL, Lausanne. I have expertise in neuroimaging and computational biology with an axis on methodologies for health big data.  
  <br><br>
  <a href="https://www.linkedin.com/in/sandrine-muller-phd-ba459725/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="/bio-sandrine">Sandrine's bio</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-EHB7LFLLGE 
