title: Scienceable lab # your name (or website title) here
logo: "/images/sandrine_portrait.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Asst. Prof. Sandrine Muller, Eng. Msc., PhD
  <br><br>
  Hey there! 
  My name is Sandrine Muller and I lead ScienceAble lab. We are glad you joined and hope you get some fun browsing our projects!
  # <br><br>
  # <a href="https://www.linkedin.com/in/sandrine-muller-phd-ba459725/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="/bio-sandrine">Sandrine's bio</a> 
# ---
profiles:
  github:
    name: GitHub
    url: https://github.com/your-github-username
    logo: https://img.shields.io/badge/-GitHub-black?style=flat&logo=github&logoColor=white

  linkedin:
    name: LinkedIn
    url: https://www.linkedin.com/in/your-linkedin-username
    logo: https://img.shields.io/badge/-LinkedIn-blue?style=flat&logo=linkedin&logoColor=white

  bluesky:
    name: Bluesky
    url: https://bsky.app/profile/your-bluesky-username
    logo: https://img.shields.io/badge/-Bluesky-00A1E4?style=flat&logo=bluesky&logoColor=white

display_text: "View My Profiles"  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-EHB7LFLLGE 
